# Generated by Django 3.1 on 2020-11-06 13:32

import chatter.utils.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dialog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', chatter.utils.models.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', chatter.utils.models.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('participants', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='participants')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', chatter.utils.models.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', chatter.utils.models.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('content', models.TextField(blank=True, null=True)),
                ('workflow_state', django_fsm.FSMField(default='sended', max_length=50)),
                ('is_removed', models.BooleanField(blank=True, default=False)),
                ('file', models.FileField(null=True, upload_to='files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg'])])),
                ('dialog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatter.dialog')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Dialog owner')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
