# Generated by Django 3.1 on 2020-09-25 15:57

from django.db import migrations, models
import django.db.models.manager
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('chatter', '0003_auto_20200922_1221'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='message',
            managers=[
                ('available_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='is_removed',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='workflow_state',
            field=django_fsm.FSMField(default='sended', max_length=50),
        ),
    ]
