# Generated by Django 3.1 on 2020-09-25 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatter', '0004_auto_20200925_1757'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='message',
            managers=[
            ],
        ),
    ]
