# Generated by Django 3.1 on 2020-10-14 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatter', '0006_auto_20201007_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
